# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=50, unique=True)),
                ('partname', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subword', models.CharField(max_length=100)),
                ('meaning', models.ManyToManyField(to='kosh.Meaning')),
                ('parentword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosh.BaseWord')),
            ],
        ),
        migrations.AddField(
            model_name='meaning',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosh.Pos'),
        ),
        migrations.AddField(
            model_name='baseword',
            name='meaning',
            field=models.ManyToManyField(to='kosh.Meaning'),
        ),
    ]
